version: '2'
services:
  db:
    image: postgres
    volumes:
      - foodery-db-sync:/var/lib/postgresql/data:nocopy
  web:
    build: .
    command: ./start_docker_development.sh
    volumes:
      - foodery-sync:/myapp:nocopy
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./config/nginx-develop.conf:/etc/nginx/conf.d/default.conf:z
      - foodery-sync:/myapp:nocopy
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - web
volumes:
  foodery-sync:
    external: true
  foodery-db-sync:
    external: true
